# Site settings
title: Engineering Portfolio
name: Andrea Solfrizzi
email: andreasolfrizzi02@gmail.com
description: >-
  Portfolio of Andrea Solfrizzi, MSc student in Advanced Automotive Engineering at MUNER, specializing in High Performance Car Design, Vehicle Dynamics, and Active Aerodynamics.
baseurl: ""
url: "https://andreasolfrizzi.github.io"

github_username: clancyisdead11

# Build settings
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme
minimal_mistakes_skin: "neon" 

# General settings
date_format: "%d-%m-%Y"
words_per_minute: 200
enable_copy_code_button: true
atom_feed:
  hide: true

search: true
lunr:
  search_within_pages: true

author:
  name     : "Andrea Solfrizzi"
  avatar   : "/assets/images/io.png"
  bio      : "MSc student in Advanced Automotive Engineering - High Performance Car Design @ MUNER."

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/andrea-solfrizzi-b5b152292/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/clancyisdead11"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      author_profile: true
      read_time: true
      share: true
      related: true
      mathjax: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false