source "https://rubygems.org"

gem "jekyll", ">= 4.3.0"
gem "jekyll-remote-theme"  # <-- Added this to fix local remote theme builds

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-include-cache"
end

gem "csv"
gem "webrick"
gem "bigdecimal"

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]